name: pozos
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2022.9.24
  - ld_impl_linux-64=2.39
  - libffi=3.3
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=1.1.1s
  - pip=22.3.1
  - python=3.9.1
  - readline=8.1.2
  - setuptools=65.5.1
  - sqlite=3.40.0
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.38.4
  - xz=5.2.6
  - zlib=1.2.13
  - pip:
    - asgiref==3.5.2
    - attrs==22.1.0
    - beautifulsoup4==4.11.1
    - django==4.1.3
    - django-bootstrap-v5==1.0.11
    - django-environ==0.9.0
    - django-geojson==4.0.0
    - django-leaflet==0.28.3
    - django-recaptcha==3.0.0
    - djangorestframework==3.14.0
    - exceptiongroup==1.0.4
    - geographiclib==2.0
    - geopy==2.3.0
    - iniconfig==1.1.1
    - mysqlclient==2.1.1
    - packaging==21.3
    - pluggy==1.0.0
    - pygments==2.14.0
    - pyparsing==3.0.9
    - pytest==7.2.0
    - pytest-django==4.5.2
    - pytz==2022.6
    - redgreenunittest==0.1.1
    - soupsieve==2.3.2.post1
    - sqlparse==0.4.3
    - tomli==2.0.1
