# Generated by Django 4.1.3 on 2022-12-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pozo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=64)),
                ('sitio', models.CharField(max_length=128)),
                ('organismo', models.CharField(max_length=128)),
                ('estado', models.CharField(max_length=128)),
                ('municipio', models.CharField(max_length=128)),
                ('acuifero', models.CharField(max_length=128)),
                ('subtipo', models.CharField(max_length=32)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('periodo', models.PositiveSmallIntegerField()),
                ('alc_total', models.FloatField(null=True)),
                ('conduct_total', models.FloatField(null=True)),
                ('sdtm_total', models.FloatField(null=True)),
            ],
        ),
    ]
