# Generated by Django 4.1.3 on 2022-12-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozo',
            name='coli_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pozo',
            name='dur_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pozo',
            name='fluor_total',
            field=models.FloatField(null=True),
        ),
    ]
