# Generated by Django 3.2.15 on 2022-11-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pozo',
            old_name='long',
            new_name='lon',
        ),
        migrations.AlterField(
            model_name='pozo',
            name='fe_calidad',
            field=models.CharField(choices=[('POTABLE - EXCELENTE', 'Potable - Excelente'), ('SIN EFECTOS EN LA SALUD - PUEDE DAR COLOR AL AGUA', 'Sin efectos en la salud - Puede dar color al agua')], max_length=256),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='semaforo',
            field=models.CharField(choices=[('VERDE', 'Verde'), ('AMARILLO', 'Amarillo'), ('ROJO', 'Rojo')], max_length=32),
        ),
    ]
