# Generated by Django 4.1.3 on 2022-12-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapi', '0002_pozo_coli_total_pozo_dur_total_pozo_fluor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozo',
            name='semaforo',
            field=models.CharField(choices=[('VERDE', 'Verde'), ('AMARILLO', 'Amarillo'), ('ROJO', 'Rojo')], default='', max_length=32),
            preserve_default=False,
        ),
    ]
