# Generated by Django 4.1.3 on 2022-12-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapi', '0003_pozo_semaforo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozo',
            name='as_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pozo',
            name='cd_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pozo',
            name='nno3_total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='semaforo',
            field=models.CharField(choices=[('Verde', 'Verde'), ('Amarillo', 'Amarillo'), ('Rojo', 'Rojo')], max_length=32),
        ),
    ]
