# Generated by Django 4.1.3 on 2023-01-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapi', '0005_pozo_cr_total_pozo_hg_total_pozo_pb_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozo',
            name='fe_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pozo',
            name='mn_total',
            field=models.FloatField(null=True),
        ),
    ]
