# Generated by Django 4.1.3 on 2023-01-31 18:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('edad', models.PositiveSmallIntegerField()),
                ('peso', models.PositiveSmallIntegerField()),
                ('sexo', models.CharField(choices=[('mujer', 'Mujer'), ('hombre', 'Hombre')], max_length=32)),
                ('agua_cocinar', models.CharField(choices=[('llave', 'De la llave'), ('garrafon', 'De garrafón'), ('filtro', 'De filtro'), ('hervida', 'Hervida'), ('otra', 'Otra')], max_length=32)),
                ('agua_tomar', models.CharField(choices=[('llave', 'De la llave'), ('garrafon', 'De garrafón'), ('filtro', 'De filtro'), ('hervida', 'Hervida'), ('otra', 'Otra')], max_length=32)),
                ('cuidador', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')])),
                ('vasos', models.PositiveSmallIntegerField(default=0)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
