# Generated by Django 4.0.7 on 2022-11-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveSmallIntegerField()),
                ('peso', models.PositiveSmallIntegerField()),
                ('sexo', models.CharField(choices=[('mujer', 'Mujer'), ('hombre', 'Hombre')], max_length=32)),
                ('agua_cocinar', models.CharField(choices=[('llave', 'De la llave'), ('garrafon', 'De garrafón'), ('filtro', 'De filtro'), ('hervida', 'Hervida'), ('otra', 'Otra')], max_length=32)),
                ('agua_tomar', models.CharField(choices=[('llave', 'De la llave'), ('garrafon', 'De garrafón'), ('filtro', 'De filtro'), ('hervida', 'Hervida'), ('otra', 'Otra')], max_length=32)),
                ('cuidador', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], verbose_name='¿Eres el o la principal cuidador de menores de edad?')),
            ],
        ),
    ]
