# Generated by Django 4.0.7 on 2022-11-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_encuesta_created_at_encuesta_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='vasos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='cuidador',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')]),
        ),
    ]
