# Generated by Django 3.2.15 on 2022-11-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_encuesta_vasos_alter_encuesta_cuidador'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='lon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
